# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import mesh_pb2 as mesh__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mesh_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentMeshStub:
    """── Orchestrator ↔ Agent gRPC Service ─────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/mesh.v1.AgentMesh/Register',
                request_serializer=mesh__pb2.AgentRegistrationRequest.SerializeToString,
                response_deserializer=mesh__pb2.AgentRegistrationResponse.FromString,
                _registered_method=True)
        self.TaskStream = channel.stream_stream(
                '/mesh.v1.AgentMesh/TaskStream',
                request_serializer=mesh__pb2.SignedPacket.SerializeToString,
                response_deserializer=mesh__pb2.SignedPacket.FromString,
                _registered_method=True)
        self.HeartBeatStream = channel.stream_unary(
                '/mesh.v1.AgentMesh/HeartBeatStream',
                request_serializer=mesh__pb2.HeartBeat.SerializeToString,
                response_deserializer=mesh__pb2.HeartBeatAck.FromString,
                _registered_method=True)
        self.PushPermissionGrant = channel.unary_unary(
                '/mesh.v1.AgentMesh/PushPermissionGrant',
                request_serializer=mesh__pb2.PermissionGrant.SerializeToString,
                response_deserializer=mesh__pb2.GrantAck.FromString,
                _registered_method=True)
        self.ReportError = channel.unary_unary(
                '/mesh.v1.AgentMesh/ReportError',
                request_serializer=mesh__pb2.ErrorReport.SerializeToString,
                response_deserializer=mesh__pb2.ErrorAck.FromString,
                _registered_method=True)
        self.IssueQuarantine = channel.unary_unary(
                '/mesh.v1.AgentMesh/IssueQuarantine',
                request_serializer=mesh__pb2.QuarantineNotice.SerializeToString,
                response_deserializer=mesh__pb2.QuarantineAck.FromString,
                _registered_method=True)


class AgentMeshServicer:
    """── Orchestrator ↔ Agent gRPC Service ─────────────────────────────────────

    """

    def Register(self, request, context):
        """Agent registers with Orchestrator; completes X25519 ECDH handshake
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskStream(self, request_iterator, context):
        """Bidirectional stream: Orchestrator dispatches tasks; Agent returns results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartBeatStream(self, request_iterator, context):
        """Unidirectional heartbeat stream from Agent to Orchestrator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushPermissionGrant(self, request, context):
        """Orchestrator pushes a permission grant update to an Agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportError(self, request, context):
        """Agent reports an error to the Orchestrator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssueQuarantine(self, request, context):
        """Orchestrator issues a quarantine notice (server-push, one-way)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentMeshServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=mesh__pb2.AgentRegistrationRequest.FromString,
                    response_serializer=mesh__pb2.AgentRegistrationResponse.SerializeToString,
            ),
            'TaskStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TaskStream,
                    request_deserializer=mesh__pb2.SignedPacket.FromString,
                    response_serializer=mesh__pb2.SignedPacket.SerializeToString,
            ),
            'HeartBeatStream': grpc.stream_unary_rpc_method_handler(
                    servicer.HeartBeatStream,
                    request_deserializer=mesh__pb2.HeartBeat.FromString,
                    response_serializer=mesh__pb2.HeartBeatAck.SerializeToString,
            ),
            'PushPermissionGrant': grpc.unary_unary_rpc_method_handler(
                    servicer.PushPermissionGrant,
                    request_deserializer=mesh__pb2.PermissionGrant.FromString,
                    response_serializer=mesh__pb2.GrantAck.SerializeToString,
            ),
            'ReportError': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportError,
                    request_deserializer=mesh__pb2.ErrorReport.FromString,
                    response_serializer=mesh__pb2.ErrorAck.SerializeToString,
            ),
            'IssueQuarantine': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueQuarantine,
                    request_deserializer=mesh__pb2.QuarantineNotice.FromString,
                    response_serializer=mesh__pb2.QuarantineAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mesh.v1.AgentMesh', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mesh.v1.AgentMesh', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentMesh:
    """── Orchestrator ↔ Agent gRPC Service ─────────────────────────────────────

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.v1.AgentMesh/Register',
            mesh__pb2.AgentRegistrationRequest.SerializeToString,
            mesh__pb2.AgentRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mesh.v1.AgentMesh/TaskStream',
            mesh__pb2.SignedPacket.SerializeToString,
            mesh__pb2.SignedPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartBeatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/mesh.v1.AgentMesh/HeartBeatStream',
            mesh__pb2.HeartBeat.SerializeToString,
            mesh__pb2.HeartBeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushPermissionGrant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.v1.AgentMesh/PushPermissionGrant',
            mesh__pb2.PermissionGrant.SerializeToString,
            mesh__pb2.GrantAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.v1.AgentMesh/ReportError',
            mesh__pb2.ErrorReport.SerializeToString,
            mesh__pb2.ErrorAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IssueQuarantine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.v1.AgentMesh/IssueQuarantine',
            mesh__pb2.QuarantineNotice.SerializeToString,
            mesh__pb2.QuarantineAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
